const SUPABASE_URL="https://xdswybtzbmtxzxcnytqn.supabase.co";
const SUPABASE_KEY="sb_publishable_2Q8BxVITxZri3doBrLep3Q_tKT_JsVG";
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});

const rooms=["Quarto 5","Quarto 6","Quarto 7","Quarto 8","Quarto 9"];
const schedule=[["2026-08-01","Quarto 9"],["2026-08-08","Quarto 5"],["2026-08-15","Quarto 6"],["2026-08-22","Quarto 7"],["2026-08-29","Quarto 8"],["2026-09-05","Quarto 9"],["2026-09-12","Quarto 5"],["2026-09-19","Quarto 6"],["2026-09-26","Quarto 7"],["2026-10-03","Quarto 8"],["2026-10-10","Quarto 9"],["2026-10-17","Quarto 5"],["2026-10-24","Quarto 6"],["2026-10-31","Quarto 7"],["2026-11-07","Quarto 8"],["2026-11-14","Quarto 9"],["2026-11-21","Quarto 5"],["2026-11-28","Quarto 6"],["2026-12-05","Quarto 7"],["2026-12-12","Quarto 8"],["2026-12-19","Quarto 9"],["2026-12-26","Quarto 5"]].map(([date,room])=>({date,room}));
let me=null,profiles=[],cleaning=[],trash=[],calMonth=new Date().getMonth(),calYear=new Date().getFullYear(),pendingTrash=null;

const skinColors={porcelain:"#f9ddcf",light:"#f6d0b1",medium_light:"#dfa67f",medium:"#bd7f58",medium_dark:"#8c593d",dark:"#5d3928",deep:"#39241c"};
const hairColors={jet_black:"#111016",soft_black:"#272129",dark_brown:"#3a241b",chocolate:"#5a3628",brown:"#744c37",auburn:"#8b3f2e",copper:"#b65b38",blonde:"#caaa68",platinum:"#e5dcc8",pink:"#c85d8d",purple:"#70439a",blue:"#435f95"};
const eyeColors={black:"#17131b",dark_brown:"#3b241f",brown:"#6a4634",hazel:"#8a7447",green:"#55775d",blue:"#557ea8",gray:"#767c88"};
const hairNames={curls_short:"Cacheado curto",curls_medium:"Cacheado médio",curls_long:"Cacheado longo",curls_bangs:"Cacheado com franja",curls_volume:"Cacheado volumoso",curls_side:"Cacheado lateral",afro:"Afro",afro_big:"Black power",straight_middle:"Liso partido ao meio",straight_long:"Liso longo",braids:"Tranças",box_braids:"Box braids"};
const accessoryNames={none:"Sem acessório",round_glasses:"Óculos redondo",cat_glasses:"Óculos gatinho",hoops:"Argolas",pearl_earrings:"Pérolas",choker:"Choker",necklace:"Colar",hair_clip:"Presilha",bow:"Laço"};
const shirtNames={purple:"Roxa",pink:"Rosa",green:"Verde",blue:"Azul",black:"Preta",white:"Branca",rainbow:"LGBT+",lesbian:"Lésbica",bi:"Bissexual",trans:"Trans",pan:"Pan",nb:"Não-binária"};

const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const br=d=>new Date(d+"T12:00:00").toLocaleDateString("pt-BR");
const today=()=>new Date().toISOString().slice(0,10);

function openAuth(mode){$("landing").classList.add("hidden");$("auth").classList.remove("hidden");$("authError").classList.add("hidden");const login=mode==="login";$("loginForm").classList.toggle("hidden",!login);$("signupForm").classList.toggle("hidden",login);$("authTitle").textContent=login?"Bem-vinda de volta!":"Crie sua conta";$("authSubtitle").textContent=login?"Faça login para continuar":"Entre para organizar tudo com a república";}
function backToLanding(){$("auth").classList.add("hidden");$("landing").classList.remove("hidden");}
function showError(e){$("authError").textContent=e?.message||e;$("authError").classList.remove("hidden");}
async function signIn(){const email=$("loginEmail").value.trim(),password=$("loginPassword").value;if($("rememberUser").checked)localStorage.setItem("banheiro_email",email);else localStorage.removeItem("banheiro_email");const {error}=await sb.auth.signInWithPassword({email,password});if(error)return showError(error);await loadApp();}
async function signUp(){const name=$("signupName").value.trim(),email=$("signupEmail").value.trim(),password=$("signupPassword").value,room=$("signupRoom").value;const {data,error}=await sb.auth.signUp({email,password,options:{data:{name,room}}});if(error)return showError(error);localStorage.setItem("banheiro_email",email);if(!data.session)return showError("Conta criada. Confirme o e-mail, se solicitado, e depois entre.");await loadApp();}
async function logout(){await sb.auth.signOut();location.reload();}

async function loadApp(){const {data:{user}}=await sb.auth.getUser();if(!user)return;let {data:p}=await sb.from("profiles").select("*").eq("id",user.id).maybeSingle();if(!p){const {error}=await sb.from("profiles").insert({id:user.id,name:user.user_metadata?.name||user.email.split("@")[0],room:user.user_metadata?.room||"Quarto 5"});if(error)return alert(error.message);({data:p}=await sb.from("profiles").select("*").eq("id",user.id).single());}me=p;$("landing").classList.add("hidden");$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("who").textContent=`${me.name} • ${me.room}`;await refresh();if(new URLSearchParams(location.search).get("quick")==="trash")setTimeout(openQuickTrash,250);}
async function refresh(){const [p,c,t]=await Promise.all([sb.from("profiles").select("*"),sb.from("cleaning_records").select("*").order("cleaning_date"),sb.from("trash_records").select("*").order("trash_date",{ascending:false})]);profiles=p.data||[];cleaning=c.data||[];trash=t.data||[];me=profiles.find(x=>x.id===me.id)||me;renderAll();}
function showTab(tab){["dash","agenda","trash","rank","profile","history"].forEach(id=>$(id).classList.toggle("hidden",id!==tab));const map={dash:"navDash",agenda:"navAgenda",trash:"navTrash",rank:"navRank",profile:"navProfile"};Object.values(map).forEach(id=>$(id)?.classList.remove("active"));if(map[tab])$(map[tab]).classList.add("active");}
const pname=id=>profiles.find(p=>p.id===id)?.name||"Morador";
const proom=id=>profiles.find(p=>p.id===id)?.room||"";
const crec=d=>cleaning.find(x=>x.cleaning_date===d);
function nextCleaning(){const d=today();return schedule.find(x=>!crec(x.date)&&x.date>=d)||schedule.find(x=>!crec(x.date));}
function myFuture(){const d=today();return schedule.filter(x=>x.room===me.room&&x.date>=d);}
async function markCleaning(date,status){const item=schedule.find(x=>x.date===date),{error}=await sb.from("cleaning_records").insert({cleaning_date:date,assigned_room:item.room,status,recorded_by:me.id});if(error)alert(error.message);else refresh();}
async function addTrash(date){const {error}=await sb.from("trash_records").insert({trash_date:date,recorded_by:me.id});if(error)alert(error.message);else refresh();}
async function delTrash(id){const {error}=await sb.from("trash_records").delete().eq("id",id);if(error)alert(error.message);else refresh();}
function countMap(){const m={};trash.forEach(x=>m[x.recorded_by]=(m[x.recorded_by]||0)+1);return m;}
const ranking=()=>Object.entries(countMap()).sort((a,b)=>b[1]-a[1]);
function myRank(){const r=ranking(),i=r.findIndex(([id])=>id===me.id);return{rank:i<0?"-":i+1,count:trash.filter(x=>x.recorded_by===me.id).length};}

function backHair(s,c,c2){const d=c2||c,m={
curls_short:`<g fill="${c}"><circle cx="75" cy="43" r="42"/><circle cx="42" cy="59" r="22"/><circle cx="108" cy="59" r="22"/></g>`,
curls_medium:`<g fill="${c}"><circle cx="75" cy="43" r="46"/><circle cx="36" cy="66" r="27"/><circle cx="114" cy="66" r="27"/><circle cx="45" cy="100" r="25"/><circle cx="105" cy="100" r="25"/></g>`,
curls_long:`<g fill="${c}"><circle cx="75" cy="42" r="47"/><circle cx="34" cy="67" r="28"/><circle cx="116" cy="67" r="28"/><rect x="27" y="64" width="96" height="95" rx="38"/></g>`,
curls_bangs:`<g fill="${c}"><circle cx="75" cy="43" r="45"/><circle cx="38" cy="66" r="25"/><circle cx="112" cy="66" r="25"/></g>`,
curls_volume:`<g fill="${c}"><circle cx="75" cy="43" r="53"/><circle cx="28" cy="66" r="31"/><circle cx="122" cy="66" r="31"/><circle cx="40" cy="113" r="32"/><circle cx="110" cy="113" r="32"/></g>`,
curls_side:`<g fill="${c}"><circle cx="75" cy="43" r="43"/><circle cx="37" cy="65" r="23"/><circle cx="117" cy="72" r="31"/><circle cx="116" cy="113" r="29"/></g>`,
afro:`<g fill="${c}"><circle cx="75" cy="49" r="58"/><circle cx="27" cy="67" r="29"/><circle cx="123" cy="67" r="29"/></g>`,
afro_big:`<g fill="${c}"><circle cx="75" cy="51" r="68"/><circle cx="23" cy="72" r="31"/><circle cx="127" cy="72" r="31"/></g>`,
straight_middle:`<path d="M30 150 Q25 14 75 10 Q125 14 120 150 L103 170 L79 90 L75 31 L71 90 L47 170Z" fill="${c}"/>`,
straight_long:`<path d="M30 160 Q25 12 75 9 Q125 12 120 160 L103 174 L47 174Z" fill="${c}"/>`,
braids:`<g><circle cx="75" cy="40" r="38" fill="${c}"/><path d="M42 54 Q31 101 37 162" stroke="${c}" stroke-width="11" fill="none" stroke-linecap="round"/><path d="M108 54 Q119 101 113 162" stroke="${d}" stroke-width="11" fill="none" stroke-linecap="round"/><path d="M34 61 Q50 83 35 103 Q52 124 37 150" stroke="${d}" stroke-width="4" fill="none"/><path d="M116 61 Q100 83 115 103 Q98 124 113 150" stroke="${c}" stroke-width="4" fill="none"/></g>`,
box_braids:`<g><circle cx="75" cy="39" r="38" fill="${c}"/><path d="M36 50 L29 164 M49 52 L43 170" stroke="${c}" stroke-width="8" stroke-linecap="round"/><path d="M101 52 L107 170 M114 50 L121 164" stroke="${d}" stroke-width="8" stroke-linecap="round"/></g>`};return m[s]||m.curls_medium;}
function frontHair(s,c){return({curls_bangs:`<g fill="${c}"><circle cx="54" cy="43" r="14"/><circle cx="72" cy="39" r="15"/><circle cx="91" cy="43" r="14"/></g>`,curls_side:`<path d="M45 40 Q55 16 91 20 Q68 39 51 64Z" fill="${c}"/>`,straight_middle:`<path d="M40 43 Q52 16 73 23 L75 31 L77 23 Q98 16 110 43 Q92 31 79 51 L75 34 L71 51 Q58 31 40 43Z" fill="${c}"/>`})[s]||"";}
function shirtColor(t){return({purple:"#7b44dc",pink:"#ed72a5",green:"#5aad67",blue:"#4f7ccf",black:"#25232a",white:"#f4f4f4"})[t]||"#fff";}
function shirtPattern(t){const b={rainbow:["#e40303","#ff8c00","#ffed00","#008026","#004dff","#750787"],lesbian:["#d52d00","#ef7627","#fff","#d162a4","#a30262"],bi:["#d60270","#d60270","#9b4f96","#0038a8","#0038a8"],trans:["#5bcffb","#f5abb9","#fff","#f5abb9","#5bcffb"],pan:["#ff218c","#ffd800","#21b1ff"],nb:["#fff430","#fff","#9c59d1","#000"]};if(!b[t])return"";const a=b[t],h=54/a.length;return a.map((c,i)=>`<rect x="45" y="${121+i*h}" width="60" height="${h+1}" fill="${c}"/>`).join("");}
function accessory(t){return({none:"",round_glasses:`<g fill="none" stroke="#a56a4e" stroke-width="2.3"><circle cx="60" cy="72" r="18"/><circle cx="90" cy="72" r="18"/><path d="M78 70 Q75 67 72 70"/></g>`,cat_glasses:`<g fill="none" stroke="#6f35d4" stroke-width="2.5"><path d="M43 66 L48 55 L76 62 L75 80 Q56 89 45 78Z"/><path d="M107 66 L102 55 L74 62 L75 80 Q94 89 105 78Z"/></g>`,hoops:`<g fill="none" stroke="#d4a326" stroke-width="3"><circle cx="43" cy="91" r="9"/><circle cx="107" cy="91" r="9"/></g>`,pearl_earrings:`<g fill="#fff" stroke="#c9c3bb"><circle cx="43" cy="91" r="5"/><circle cx="107" cy="91" r="5"/></g>`,choker:`<rect x="57" y="112" width="36" height="5" rx="2.5" fill="#1e1b22"/>`,necklace:`<path d="M55 113 Q75 132 95 113" fill="none" stroke="#caa43a" stroke-width="2"/><circle cx="75" cy="130" r="3" fill="#caa43a"/>`,hair_clip:`<rect x="102" y="43" width="17" height="5" rx="2.5" fill="#ef7cac" transform="rotate(18 110 45)"/>`,bow:`<g fill="#e75f9d"><path d="M101 31 Q88 23 92 42Z"/><path d="M109 31 Q122 23 118 42Z"/><circle cx="105" cy="33" r="5"/></g>`})[t]||"";}
function avatar(p={}){const skin=skinColors[p.avatar_skin]||skinColors.medium,hair=hairColors[p.avatar_hair_color]||hairColors.dark_brown,hair2=hairColors[p.avatar_hair_color_2]||hair,eye=eyeColors[p.avatar_eyes]||eyeColors.dark_brown,style=p.avatar_hair||"curls_medium",shirt=p.avatar_shirt||"purple";let details="";if(p.avatar_freckles)details+=`<g fill="#9a5f48" opacity=".55"><circle cx="60" cy="87" r="1.2"/><circle cx="66" cy="89" r="1.1"/><circle cx="90" cy="87" r="1.2"/><circle cx="84" cy="89" r="1.1"/></g>`;if(p.avatar_beauty_mark)details+=`<circle cx="96" cy="100" r="1.8" fill="#4b2a26"/>`;return `<svg viewBox="0 0 150 190" xmlns="http://www.w3.org/2000/svg">${backHair(style,hair,hair2)}<path d="M46 180 Q47 119 75 116 Q103 119 104 180Z" fill="${shirtColor(shirt)}"/>${shirtPattern(shirt)}<rect x="67" y="104" width="16" height="18" rx="7" fill="${skin}"/><ellipse cx="75" cy="76" rx="37" ry="43" fill="${skin}"/><ellipse cx="60" cy="74" rx="12.5" ry="15" fill="#fff"/><ellipse cx="90" cy="74" rx="12.5" ry="15" fill="#fff"/><circle cx="60" cy="76" r="8.3" fill="${eye}"/><circle cx="90" cy="76" r="8.3" fill="${eye}"/><circle cx="58" cy="73" r="3.2" fill="#fff"/><circle cx="88" cy="73" r="3.2" fill="#fff"/><path d="M49 58 Q60 52 69 58 M81 58 Q91 52 101 58" stroke="${hair}" stroke-width="3" fill="none" stroke-linecap="round"/><path d="M70 88 Q75 91 80 88" stroke="#a45e53" stroke-width="1.7" fill="none"/><path d="M65 98 Q75 106 85 98 Q75 112 65 98Z" fill="#c75864"/><circle cx="49" cy="89" r="5" fill="#e9878e" opacity=".22"/><circle cx="101" cy="89" r="5" fill="#e9878e" opacity=".22"/>${details}${frontHair(style,hair)}${accessory(p.avatar_accessory||"none")}</svg>`;}

function renderDashboard(){const n=nextCleaning(),m=myRank(),top=ranking().slice(0,4),slots=[["💎🏆","first","⭐"],["🥇","second",""],["🥈","third",""],["🥉","fourth","⚠️"]];const cards=slots.map((s,i)=>{const r=top[i];if(!r)return`<div class="rank-card ${s[1]==="first"?"first":""}"><div class="rank-trophy">${s[0]}</div><div class="rank-name ${s[1]}">Sem usuário</div><div class="rank-count">0</div></div>`;const p=profiles.find(x=>x.id===r[0])||{};return`<div class="rank-card ${s[1]==="first"?"first":""}"><div class="rank-trophy">${s[0]}</div><div class="rank-person"><div class="rank-avatar">${avatar(p)}</div><div><div class="rank-name ${s[1]}">${esc(p.name)} ${s[2]}</div><small>${esc(p.room)}</small></div></div><div class="rank-count">${r[1]} <small>retiradas</small></div></div>`}).join("");$("dash").innerHTML=`<h2>Olá, ${esc(me.name)}! 👋</h2><div class="stats"><div class="stat"><b>${cleaning.filter(x=>x.status==="done").length}</b><small>Limpezas feitas</small></div><div class="stat"><b>${cleaning.filter(x=>x.status==="late").length}</b><small>Atrasos</small></div><div class="stat"><b>${m.count}</b><small>Lixos registrados</small></div><div class="stat"><b>${m.rank}</b><small>Sua posição</small></div></div><div class="next"><small>PRÓXIMA LIMPEZA</small>${n?`<b>${n.room}</b><span>📅 ${br(n.date)}</span>`:`<b>Tudo concluído!</b>`}</div><h3>🏆 Ranking do lixo</h3><div class="rank-grid">${cards}</div><button class="btn green wide" onclick="openQuickTrash()">🗑️ Registrar lixo rápido</button>`;}
function renderAgenda(){$("agenda").innerHTML=`<h2>🧹 Rodízio de limpeza</h2>`+schedule.map(x=>{const r=crec(x.date);return`<div class="card"><div class="row"><div><b>${x.room}</b><small>${br(x.date)}</small></div><span class="badge ${r?.status==="done"?"ok":r?.status==="late"?"late":""}">${r?.status==="done"?"✓ FEITO":r?.status==="late"?"⚠ ATRASADO":"PENDENTE"}</span></div>${!r?`<div class="actions"><button class="small-btn done" onclick="markCleaning('${x.date}','done')">✓ Marcar feito</button><button class="small-btn danger" onclick="markCleaning('${x.date}','late')">⚠ Atraso</button></div>`:`<small>Por ${esc(pname(r.recorded_by))} • ${new Date(r.recorded_at).toLocaleString("pt-BR")}</small>`}</div>`}).join("");}
function renderTrash(){const first=new Date(calYear,calMonth,1),last=new Date(calYear,calMonth+1,0),start=(first.getDay()+6)%7,d0=today();let days="";for(let i=0;i<start;i++)days+=`<div class="cal-day empty"></div>`;for(let d=1;d<=last.getDate();d++){const ds=`${calYear}-${String(calMonth+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,rs=trash.filter(x=>x.trash_date===ds);days+=`<div class="cal-day ${rs.length?"registered":""} ${ds===d0?"today":""}"><span class="num">${d}</span>${rs.map(x=>`<span class="mark">● ${esc(pname(x.recorded_by))}</span>`).join("")}<button onclick="addTrash('${ds}')">+ registrar</button></div>`}$("trash").innerHTML=`<h2>🗑️ Registro do lixo</h2><div class="card calendar-card"><div class="cal-toolbar"><button onclick="changeMonth(-1)">‹</button><b>${first.toLocaleString("pt-BR",{month:"long",year:"numeric"})}</b><button onclick="changeMonth(1)">›</button></div><div class="cal-week"><span>SEG</span><span>TER</span><span>QUA</span><span>QUI</span><span>SEX</span><span>SÁB</span><span>DOM</span></div><div class="cal-grid">${days}</div><div class="legend"><span><i class="dot" style="background:#20b65d"></i>Lixo registrado</span><span><i class="dot" style="background:#7137d8"></i>Hoje</span></div></div><button class="btn green wide" onclick="openQuickTrash()">＋ Registrar lixo hoje</button><div class="card"><h3>Registros recentes</h3>${trash.slice(0,30).map(x=>`<div class="recent row"><span>${br(x.trash_date)} — <b>${esc(pname(x.recorded_by))}</b> ${proom(x.recorded_by)?`(${esc(proom(x.recorded_by))})`:""}</span>${x.recorded_by===me.id?`<button class="small-btn" onclick="delTrash(${x.id})">✕</button>`:""}</div>`).join("")||"<small>Nenhum registro ainda.</small>"}</div>`;}
function changeMonth(n){calMonth+=n;if(calMonth<0){calMonth=11;calYear--}if(calMonth>11){calMonth=0;calYear++}renderTrash();}
function renderRank(){$("rank").innerHTML=`<h2>🏆 Ranking completo</h2><div class="card"><table><thead><tr><th>#</th><th>Pessoa</th><th>Quarto</th><th>Lixo</th></tr></thead><tbody>${ranking().map(([id,c],i)=>`<tr><td>${i+1}</td><td><b>${esc(pname(id))}</b></td><td>${esc(proom(id))}</td><td>${c}</td></tr>`).join("")}</tbody></table></div>`;}
async function upd(f,v){const {error}=await sb.from("profiles").update({[f]:v}).eq("id",me.id);if(error)return alert(error.message);me[f]=v;renderProfile();renderDashboard();}
async function saveProfile(){const name=$("profileName").value.trim(),room=$("profileRoom").value,{error}=await sb.from("profiles").update({name,room}).eq("id",me.id);if(error)return alert(error.message);await refresh();$("who").textContent=`${me.name} • ${me.room}`;}
function hairPreview(style){return avatar({...me,avatar_hair:style});}
function renderProfile(){const m=myRank(),future=myFuture(),braid=["braids","box_braids"].includes(me.avatar_hair||"");$("profile").innerHTML=`<h2>👤 Meu perfil</h2><div class="card profile-top"><div class="avatar-card"><div class="avatar-big">${avatar(me)}</div><b>${esc(me.name)}</b><div><small>${esc(me.room)}</small></div></div><div><div class="editor"><div class="field"><label>Nome</label><input id="profileName" value="${esc(me.name)}"></div><div class="field"><label>Quarto</label><select id="profileRoom">${rooms.map(r=>`<option ${r===me.room?"selected":""}>${r}</option>`).join("")}</select></div></div><button class="btn primary" onclick="saveProfile()">Salvar</button></div></div>
<div class="card"><h3>🎨 Personalizar caricatura</h3>
<div class="avatar-section"><h4>Tom de pele</h4><div class="colors">${Object.entries(skinColors).map(([k,c])=>`<button class="color ${me.avatar_skin===k?"active":""}" style="background:${c}" onclick="upd('avatar_skin','${k}')"></button>`).join("")}</div></div>
<div class="avatar-section"><h4>Cabelo</h4><div class="hair-grid">${Object.entries(hairNames).map(([k,l])=>`<button class="hair-choice ${me.avatar_hair===k?"active":""}" onclick="upd('avatar_hair','${k}')"><div class="mini-avatar">${hairPreview(k)}</div>${l}</button>`).join("")}</div></div>
<div class="avatar-section"><h4>Cor principal do cabelo</h4><div class="colors">${Object.entries(hairColors).map(([k,c])=>`<button class="color ${me.avatar_hair_color===k?"active":""}" style="background:${c}" onclick="upd('avatar_hair_color','${k}')"></button>`).join("")}</div></div>
${braid?`<div class="avatar-section"><h4>Segunda cor das tranças</h4><div class="colors">${Object.entries(hairColors).map(([k,c])=>`<button class="color ${me.avatar_hair_color_2===k?"active":""}" style="background:${c}" onclick="upd('avatar_hair_color_2','${k}')"></button>`).join("")}</div></div>`:""}
<div class="avatar-section"><h4>Cor dos olhos</h4><div class="colors">${Object.entries(eyeColors).map(([k,c])=>`<button class="color ${me.avatar_eyes===k?"active":""}" style="background:${c}" onclick="upd('avatar_eyes','${k}')"></button>`).join("")}</div></div>
<div class="avatar-section"><h4>Blusa</h4><div class="options">${Object.entries(shirtNames).map(([k,l])=>`<button class="option ${me.avatar_shirt===k?"active":""}" onclick="upd('avatar_shirt','${k}')">${l}</button>`).join("")}</div></div>
<div class="avatar-section"><h4>Acessórios</h4><div class="options">${Object.entries(accessoryNames).map(([k,l])=>`<button class="option ${(me.avatar_accessory||"none")===k?"active":""}" onclick="upd('avatar_accessory','${k}')">${l}</button>`).join("")}</div></div>
<div class="avatar-section"><h4>Detalhes</h4><div class="options"><button class="option ${me.avatar_freckles?"active":""}" onclick="upd('avatar_freckles',${!me.avatar_freckles})">Sardas</button><button class="option ${me.avatar_beauty_mark?"active":""}" onclick="upd('avatar_beauty_mark',${!me.avatar_beauty_mark})">Pintinha</button></div></div></div>
<div class="stats"><div class="stat"><b>${m.count}</b><small>vezes que tirou lixo</small></div><div class="stat"><b>${m.rank}</b><small>posição no ranking</small></div></div>
<div class="card"><h3>🧹 Próximos dias</h3>${future.map(x=>`<div class="recent"><b>${br(x.date)}</b> • ${x.room}</div>`).join("")||"<small>Nenhuma data futura.</small>"}<div class="actions"><button class="btn primary" onclick="downloadICS()">📥 Baixar calendário</button><button class="btn light" onclick="googleNext()">📅 Google Agenda</button></div></div>`;}
function renderHistory(){const items=[];cleaning.forEach(x=>items.push({a:x.recorded_at,h:`🧹 ${br(x.cleaning_date)} — <b>${x.assigned_room}</b> — ${x.status==="done"?"feito":"atrasado"} — ${esc(pname(x.recorded_by))}`}));trash.forEach(x=>items.push({a:x.recorded_at,h:`🗑️ ${br(x.trash_date)} — <b>${esc(pname(x.recorded_by))}</b> tirou o lixo`}));items.sort((a,b)=>new Date(b.a)-new Date(a.a));$("history").innerHTML=`<h2>📜 Histórico</h2>${items.slice(0,100).map(x=>`<div class="card">${x.h}</div>`).join("")}`;}
function renderAll(){renderDashboard();renderAgenda();renderTrash();renderRank();renderProfile();renderHistory();}
function openQuickTrash(){pendingTrash=today();$("quickTrashText").innerHTML=`Registrar que <b>${esc(me?.name||"você")}</b> tirou o lixo hoje, <b>${br(pendingTrash)}</b>?`;$("quickTrashModal").classList.remove("hidden");}
function closeQuickTrash(){$("quickTrashModal").classList.add("hidden");pendingTrash=null;}
async function confirmQuickTrash(){const d=pendingTrash;closeQuickTrash();if(d)await addTrash(d);}
function icsDate(date,h){const [y,m,d]=date.split("-");return `${y}${m}${d}T${String(h).padStart(2,"0")}0000`;}
function downloadICS(){const ev=myFuture();if(!ev.length)return alert("Sem datas futuras.");const l=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Banheiro Apto 101//PT-BR","CALSCALE:GREGORIAN"];ev.forEach(x=>l.push("BEGIN:VEVENT",`UID:${x.date}-${me.room.replace(/\s/g,"")}@banheiro-apto101`,`DTSTART;TZID=America/Sao_Paulo:${icsDate(x.date,9)}`,`DTEND;TZID=America/Sao_Paulo:${icsDate(x.date,10)}`,"SUMMARY:🧹 Lavar o banheiro",`DESCRIPTION:Responsável: ${me.room}`,"BEGIN:VALARM","TRIGGER:-P1D","ACTION:DISPLAY","DESCRIPTION:Amanhã é seu dia de lavar o banheiro","END:VALARM","BEGIN:VALARM","TRIGGER:-PT2H","ACTION:DISPLAY","DESCRIPTION:Hoje é seu dia de lavar o banheiro","END:VALARM","END:VEVENT"));l.push("END:VCALENDAR");const blob=new Blob([l.join("\r\n")],{type:"text/calendar;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="limpeza-banheiro-apto-101.ics";a.click();}
function googleNext(){const x=myFuture()[0];if(!x)return alert("Sem próxima data.");window.open(`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent("🧹 Lavar o banheiro")}&dates=${icsDate(x.date,9)}/${icsDate(x.date,10)}&ctz=America%2FSao_Paulo&details=${encodeURIComponent("Responsável: "+me.room)}`,"_blank");}
const remembered=localStorage.getItem("banheiro_email");if(remembered)$("loginEmail").value=remembered;sb.auth.getSession().then(({data})=>{if(data.session)loadApp();});
